services:
  app:
    image: node:18-buster
    command: sh -c "npm install && npm start"
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      DISCORD_TOKEN: NOTSET
      APP_ID: 1173867202047381505
      AUTHORISED_USERS: 438120735722962945,178369784839143424
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: fennec
      MYSQL_DB: mwd
      
  mysql:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: fennec
      MYSQL_DATABASE: mwd

volumes:
  mysql-data: