services:
  app:
    image: node:18-buster
    command: sh -c "npm install && npm start"
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      DISCORD_TOKEN: /run/secrets/discord_token
      APP_ID: 1173867202047381505
      AUTHORISED_USERS: 438120735722962945,178369784839143424
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: /run/secrets/db_root_password
      MYSQL_DB: mwd
    secrets:
      - db_root_password
      - discord_token

  mysql:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/db_root_password
      MYSQL_DATABASE: mwd
    secrets:
      - db_root_password

secrets:
  discord_token:
    file: discord_token.txt
  db_root_password:
    file: db_root_password.txt

volumes:
  mysql-data: